/** Monsoon Atlas landing page: cinematic destination photography paired with a route-first editorial narrative. */
import { ArrowRight, CalendarDays, Check, Compass, MapPinned, MoveRight, Navigation, Sparkles, WalletCards } from "lucide-react";
import { Link } from "wouter";
import SiteFooter from "@/components/SiteFooter";
import SiteHeader from "@/components/SiteHeader";
import RouteMotif from "@/components/RouteMotif";
import { INDIAN_DESTINATIONS, formatInr } from "@/lib/tripData";

const preview = ["Masala chai at Sahu", "Amber Fort ramparts", "Lunch in the old city", "Hawa Mahal blue hour"];
const steps = [{ number: "01", title: "Tell us your intent", description: "A few thoughtful choices around place, pace, people and spending." }, { number: "02", title: "We shape the route", description: "TripsForge turns your priorities into a sequence that makes practical sense." }, { number: "03", title: "Make it yours", description: "Save moments, swap stops, lower the spend or slow the day down." }];
const features = [{ icon: Compass, title: "Route intelligence", text: "A day that flows forward, not back and forth across the map." }, { icon: WalletCards, title: "Budget with context", text: "Know where the money goes before the journey does." }, { icon: Sparkles, title: "Flexible by design", text: "Refine one moment without undoing the whole plan." }];

export default function Home() {
  return <div className="min-h-screen bg-[#fffdf8] text-[#123a35]"><SiteHeader />
    <main>
      <section className="relative overflow-hidden bg-[#f2eddf] px-5 pb-14 pt-9 lg:px-10 lg:pb-24 lg:pt-14"><div className="absolute right-[28%] top-[-11rem] h-80 w-80 rounded-full border-[36px] border-[#e6651b]/10" /><RouteMotif className="absolute -right-2 top-14 hidden h-[350px] w-[150px] opacity-70 lg:block" />
        <div className="relative mx-auto grid max-w-[1440px] items-center gap-12 lg:grid-cols-[.95fr_1.05fr] lg:gap-16">
          <div className="max-w-[630px] lg:py-10"><div className="atlas-label inline-flex items-center gap-2 rounded-full border border-[#123a35]/15 bg-[#fffdf8]/70 px-3 py-2 text-[#315d56]"><span className="h-2 w-2 rounded-full bg-[#e6651b]" /> Plans made for the way you move</div>
            <h1 className="mt-6 font-display text-[3.5rem] leading-[.91] tracking-[-.07em] text-[#123a35] sm:text-[4.7rem] lg:text-[5.7rem]">Your next trip, <em className="font-display text-[#e6651b]">forged</em> around you.</h1>
            <p className="mt-7 max-w-xl text-lg leading-8 text-[#476761]">Tell TripsForge where you want to go, what you love, and what you want to spend. We’ll build the itinerary.</p>
            <div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/planner" className="inline-flex items-center justify-center gap-2 rounded-full bg-[#123a35] px-6 py-3.5 text-sm font-bold text-white shadow-[0_14px_30px_-16px_rgba(18,58,53,.7)] transition-all hover:bg-[#1d514a] active:scale-[.97]">Plan my trip <ArrowRight className="h-4 w-4 text-[#ffb34b]" /></Link><Link href="/explore" className="inline-flex items-center justify-center gap-2 rounded-full border border-[#123a35]/20 bg-[#fffdf8]/70 px-6 py-3.5 text-sm font-bold text-[#123a35] transition-colors hover:bg-white">Explore destinations <MoveRight className="h-4 w-4" /></Link></div>
            <div className="mt-10 flex flex-wrap gap-x-7 gap-y-3 text-sm font-semibold text-[#51736b]"><span className="flex items-center gap-2"><Check className="h-4 w-4 text-[#e6651b]" /> Personal to your priorities</span><span className="flex items-center gap-2"><Check className="h-4 w-4 text-[#e6651b]" /> Budget-aware by default</span></div>
          </div>
          <div className="relative mx-auto w-full max-w-[710px] lg:mr-0"><div className="relative h-[430px] overflow-hidden rounded-[2.35rem] shadow-[0_32px_60px_-32px_rgba(18,58,53,.65)] sm:h-[560px]"><img src="/manus-storage/tripforge-hero-jaipur_1a3ec5fc.jpg" alt="Jaipur in warm golden light" className="h-full w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-[#123a35]/45 via-transparent to-transparent" /><div className="absolute right-5 top-5 flex items-center gap-2 rounded-full bg-[#fffdf8]/90 px-3 py-2 text-xs font-bold text-[#123a35] shadow-lg"><Navigation className="h-3.5 w-3.5 text-[#e6651b]" /> Jaipur, Rajasthan</div></div>
            <div className="route-thread absolute -bottom-5 left-[-18px] h-24 w-16" />
            <div className="absolute -bottom-8 left-4 w-[min(345px,calc(100%-2rem))] rounded-2xl border border-white/80 bg-[#fffdf8]/95 p-4 shadow-[0_20px_45px_-22px_rgba(18,58,53,.7)] sm:left-8 sm:p-5"><div className="flex items-center justify-between"><div><p className="atlas-label text-[#e6651b]">Your Jaipur route</p><p className="mt-1 font-display text-xl tracking-[-.04em]">Day 01 · Old city glow</p></div><span className="grid h-9 w-9 place-items-center rounded-full bg-[#123a35] text-xs font-black text-[#ffb34b]">01</span></div><div className="mt-4 grid gap-2">{preview.slice(0, 3).map((item, index) => <div key={item} className="flex items-center gap-3 text-xs font-semibold text-[#315d56]"><span className="w-9 font-mono text-[#829a94]">{["09:00", "10:30", "14:00"][index]}</span><span className="h-1.5 w-1.5 rounded-full bg-[#e6651b]" />{item}</div>)}</div></div>
          </div>
        </div>
      </section>

      <section id="how-it-works" className="relative overflow-hidden px-5 py-24 lg:px-10 lg:py-32"><RouteMotif className="absolute -left-3 bottom-8 hidden h-[250px] w-[125px] rotate-180 opacity-50 lg:block" /><div className="relative mx-auto max-w-[1440px]"><div className="flex max-w-2xl flex-col gap-5"><p className="atlas-label text-[#e6651b]">The TripsForge method</p><h2 className="font-display text-4xl leading-[.98] tracking-[-.06em] sm:text-5xl">Planning that starts with your <em>actual</em> priorities.</h2><p className="text-lg leading-8 text-[#5d7771]">You give the direction. We do the considered work of turning it into a route with room for discovery.</p></div><div className="mt-14 grid gap-0 lg:grid-cols-3">{steps.map((step, index) => <article key={step.number} className="relative border-t border-[#123a35]/15 py-7 lg:border-l lg:border-t-0 lg:px-8 lg:first:pl-0"><span className="font-mono text-sm font-bold text-[#e6651b]">{step.number}</span><h3 className="mt-8 font-display text-3xl tracking-[-.05em]">{step.title}</h3><p className="mt-4 max-w-xs leading-7 text-[#5d7771]">{step.description}</p>{index < 2 && <div className="absolute right-[-9px] top-9 hidden h-4 w-4 rounded-full border-[3px] border-[#fffdf8] bg-[#e6651b] lg:block" />}</article>)}</div></div></section>

      <section className="overflow-hidden bg-[#123a35] px-5 py-20 text-white lg:px-10 lg:py-28"><div className="mx-auto grid max-w-[1440px] items-center gap-14 lg:grid-cols-[.88fr_1.12fr]"><div><p className="atlas-label text-[#ffb34b]">One plan. Many dimensions.</p><h2 className="mt-5 font-display text-4xl leading-[.98] tracking-[-.06em] sm:text-5xl">The details, without the planning rabbit hole.</h2><p className="mt-6 max-w-md text-lg leading-8 text-[#bfd1c8]">From first breakfast to final view, every stop arrives with time, cost, distance and a reason it belongs there.</p><Link href="/itinerary" className="mt-8 inline-flex items-center gap-2 border-b border-[#ffb34b] pb-2 text-sm font-bold text-[#ffb34b] transition-all hover:gap-3">See a live itinerary <ArrowRight className="h-4 w-4" /></Link></div>
        <div className="rounded-[2rem] bg-[#f9f7ef] p-5 text-[#123a35] shadow-2xl sm:p-7"><div className="flex flex-wrap items-start justify-between gap-4 border-b border-[#123a35]/10 pb-5"><div><p className="atlas-label text-[#e6651b]">Jaipur · day 01</p><h3 className="mt-2 font-display text-3xl tracking-[-.05em]">Arrival & city exploration</h3></div><div className="rounded-xl bg-[#e5f0e9] px-3 py-2 text-right"><p className="text-xs font-bold text-[#55756c]">Trip fit</p><p className="font-display text-xl">98/100</p></div></div><div className="mt-4 divide-y divide-[#123a35]/10">{preview.map((item, index) => <div key={item} className="grid grid-cols-[54px_1fr_auto] items-center gap-3 py-4"><span className="font-mono text-xs font-bold text-[#68837c]">{["09:00", "10:30", "14:00", "18:30"][index]}</span><div><p className="text-sm font-bold">{item}</p><p className="mt-1 text-xs text-[#658078]">{["A local beginning", "History & architecture", "Your food chapter", "A view worth waiting for"][index]}</p></div><span className="text-xs font-bold text-[#e6651b]">{index === 3 ? "Free" : formatInr([120, 200, 520][index] || 0)}</span></div>)}</div></div>
      </div></section>

      <section className="px-5 py-24 lg:px-10 lg:py-32"><div className="mx-auto max-w-[1440px]"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="atlas-label text-[#e6651b]">Not a generic itinerary</p><h2 className="mt-4 font-display text-4xl tracking-[-.06em] sm:text-5xl">Small details that change the whole trip.</h2></div><p className="max-w-sm leading-7 text-[#5d7771]">Planning clarity should make travel feel more open, not more programmed.</p></div><div className="mt-12 grid gap-5 md:grid-cols-3">{features.map(({ icon: Icon, title, text }) => <article key={title} className="relative overflow-hidden rounded-[1.75rem] bg-[#f2eddf] p-7 text-[#123a35]"><span className="absolute right-6 top-6 grid h-8 w-8 place-items-center rounded-full border border-[#e6651b]/30 text-[10px] font-black text-[#e6651b]">→</span><Icon className="h-6 w-6 text-[#e6651b]" /><h3 className="mt-12 font-display text-3xl tracking-[-.05em]">{title}</h3><p className="mt-3 leading-7 text-[#5d7771]">{text}</p></article>)}</div></div></section>

      <section className="bg-[#f7f2e7] px-5 py-24 lg:px-10 lg:py-32"><div className="mx-auto max-w-[1440px]"><div className="flex items-end justify-between gap-6"><div><p className="atlas-label text-[#e6651b]">Go somewhere with a point of view</p><h2 className="mt-4 font-display text-4xl tracking-[-.06em] sm:text-5xl">Start with a destination.</h2></div><Link href="/explore" className="hidden items-center gap-2 text-sm font-bold text-[#123a35] md:inline-flex">Explore all <ArrowRight className="h-4 w-4" /></Link></div><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{INDIAN_DESTINATIONS.slice(0, 4).map((destination, index) => <Link href="/explore" key={destination.name} className={`group relative min-h-[370px] overflow-hidden rounded-[1.8rem] ${index === 0 ? "lg:col-span-2" : ""}`}><img src={destination.image} alt={destination.name} className="absolute inset-0 h-full w-full object-cover transition duration-500 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-[#0d2c28]/75 via-[#0d2c28]/10 to-transparent" /><div className="absolute bottom-0 left-0 right-0 p-5 text-white"><p className="atlas-label text-[#ffcd78]">{destination.category}</p><div className="mt-2 flex items-end justify-between gap-4"><div><h3 className="font-display text-3xl tracking-[-.05em]">{destination.name}</h3><p className="mt-1 text-xs text-white/75">From {formatInr(destination.price)}</p></div><span className="grid h-9 w-9 place-items-center rounded-full bg-white text-[#123a35] transition-transform group-hover:translate-x-1"><ArrowRight className="h-4 w-4" /></span></div></div></Link>)}</div><Link href="/explore" className="mt-8 inline-flex items-center gap-2 text-sm font-bold text-[#123a35] md:hidden">Explore all destinations <ArrowRight className="h-4 w-4" /></Link></div></section>

      <section className="px-5 py-24 lg:px-10 lg:py-32"><div className="mx-auto max-w-[1440px] overflow-hidden rounded-[2.5rem] bg-[#e6651b] px-7 py-14 text-center text-white sm:px-12 lg:px-24 lg:py-24"><p className="atlas-label text-[#ffe1a9]">Your route is waiting</p><h2 className="mx-auto mt-5 max-w-3xl font-display text-5xl leading-[.94] tracking-[-.07em] sm:text-6xl">Turn “someday” into a day-by-day plan.</h2><p className="mx-auto mt-6 max-w-xl text-lg leading-8 text-white/85">No unwieldy tabs. No vague inspiration. Just a well-shaped trip you can make your own.</p><Link href="/planner" className="mt-8 inline-flex items-center gap-2 rounded-full bg-[#123a35] px-6 py-3.5 text-sm font-bold text-white transition-all hover:bg-[#0d2c28] active:scale-[.97]">Forge my trip <Compass className="h-4 w-4 text-[#ffb34b]" /></Link></div></section>
    </main><SiteFooter /></div>;
}
