/** Monsoon Atlas itinerary: expandable daily route cards paired with a sticky, replaceable map visualization. */
import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import { ArrowLeft, CalendarDays, ChevronDown, Compass, Download, Heart, MapPin, MoreHorizontal, Navigation, PencilLine, RefreshCw, Share2, Sparkles, Timer, UsersRound, WalletCards } from "lucide-react";
import { Link } from "wouter";
import SiteHeader from "@/components/SiteHeader";
import RouteMap from "@/components/RouteMap";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { useTrip } from "@/contexts/TripContext";
import { formatDateRange, formatInr, type Activity, type ForgedTrip } from "@/lib/tripData";

const stages = ["Planning your adventure…", "Finding the best experiences…", "Balancing your budget…", "Optimizing your route…"];
const hues: Record<string, string> = { Food: "bg-[#fff0db] text-[#b34a15]", History: "bg-[#eee6dc] text-[#795a3e]", Architecture: "bg-[#e7edf6] text-[#38557c]", Photography: "bg-[#eee3f5] text-[#72498a]", Culture: "bg-[#e7f0e6] text-[#3f7248]", Nature: "bg-[#e0efe4] text-[#357044]", Adventure: "bg-[#e4edf6] text-[#365f83]", Beaches: "bg-[#dff2f0] text-[#28726e]", Shopping: "bg-[#f8e4ea] text-[#9c4961]", Nightlife: "bg-[#eee4fa] text-[#6c4d92]", Family: "bg-[#fff0d9] text-[#945d15]", "Local pick": "bg-[#f2eddf] text-[#6e6958]" };

function DaySkeleton() { return <div className="rounded-2xl border border-[#123a35]/10 bg-[#fffdf8] p-5"><div className="h-4 w-24 animate-pulse rounded bg-[#dcebe3]" /><div className="mt-4 h-8 w-2/3 animate-pulse rounded bg-[#eef4ef]" /><div className="mt-5 grid gap-3">{[1, 2, 3].map((item) => <div className="h-14 animate-pulse rounded-xl bg-[#f4f0e6]" key={item} />)}</div></div>; }

export default function Itinerary() {
  const { trip, isGenerating, finishGeneration, updateTrip } = useTrip(); const [stage, setStage] = useState(0); const [activeDay, setActiveDay] = useState(0); const [selectedId, setSelectedId] = useState(trip.days[0]?.activities[0]?.id); const [saved, setSaved] = useState<string[]>([]); const [replaceTarget, setReplaceTarget] = useState<Activity | null>(null);
  useEffect(() => { if (!isGenerating) return; setStage(0); const timer = window.setInterval(() => setStage((current) => { if (current >= stages.length - 1) { window.clearInterval(timer); window.setTimeout(finishGeneration, 650); return current; } return current + 1; }), 830); return () => window.clearInterval(timer); }, [isGenerating, finishGeneration]);
  const day = trip.days[activeDay] ?? trip.days[0];
  const travellers = trip.plan.adults + trip.plan.children;
  const activityCount = useMemo(() => trip.days.reduce((sum, item) => sum + item.activities.length, 0), [trip.days]);
  const saveActivity = (id: string) => { setSaved((items) => items.includes(id) ? items.filter((item) => item !== id) : [...items, id]); toast.success(saved.includes(id) ? "Removed from saved moments" : "Saved to your trip notes"); };
  const adjustDay = (kind: "cheaper" | "relaxed" | "regenerate") => { const updatedDays = trip.days.map((item, index) => { if (index !== activeDay) return item; if (kind === "cheaper") return { ...item, activities: item.activities.map((activity) => ({ ...activity, cost: Math.round(activity.cost * 0.75) })) }; if (kind === "relaxed" && item.activities.length > 3) return { ...item, subtitle: `${item.activities.length - 1} unhurried route moments • more space between anchors`, activities: item.activities.slice(0, -1) }; return { ...item, subtitle: `${item.activities.length} route moments • refreshed around your preferences`, activities: [...item.activities.slice(1), item.activities[0]].map((activity, index) => ({ ...activity, marker: index + 1 })) }; }); updateTrip({ ...trip, days: updatedDays }); toast.success(kind === "cheaper" ? "Costs adjusted with lower-spend alternatives" : kind === "relaxed" ? "One stop removed for more breathing room" : "Day route refreshed"); };
  const replaceActivity = () => { if (!replaceTarget) return; const updatedDays = trip.days.map((item) => ({ ...item, activities: item.activities.map((activity) => activity.id === replaceTarget.id ? { ...activity, title: `Local alternative: ${activity.title}`, description: "A fresh, nearby option that keeps your route coherent.", cost: Math.max(0, Math.round(activity.cost * 0.85)) } : activity) })); updateTrip({ ...trip, days: updatedDays }); setReplaceTarget(null); toast.success("A nearby alternative is now on your route"); };
  const share = async () => { try { await navigator.clipboard.writeText(`${trip.destination.name} itinerary by TripsForge — ${formatDateRange(trip.plan.startDate, trip.plan.endDate)}`); toast.success("Trip link copied to your clipboard"); } catch { toast.success("Share link ready to send"); } };
  if (isGenerating) return <div className="min-h-screen bg-[#f7f2e7] text-[#123a35]"><SiteHeader /><main className="mx-auto max-w-5xl px-5 py-12 lg:px-10 lg:py-20"><div className="rounded-[2.2rem] bg-[#123a35] px-6 py-10 text-center text-white shadow-[0_25px_60px_-32px_rgba(18,58,53,.65)] sm:px-10 sm:py-14"><div className="relative mx-auto grid h-16 w-16 place-items-center rounded-full border border-[#ffb34b]/50"><Compass className="h-7 w-7 animate-[spin_4s_linear_infinite] text-[#ffb34b]" /><span className="absolute inset-[-5px] rounded-full border border-dashed border-[#ffb34b]/40" /></div><p className="mt-7 atlas-label text-[#ffb34b]">TripsForge is working</p><h1 className="mt-3 font-display text-4xl tracking-[-.06em] sm:text-5xl">{stages[stage]}</h1><p className="mx-auto mt-4 max-w-md text-sm leading-6 text-[#c3d5cc]">We’re assembling the trip pieces into an itinerary with a useful rhythm.</p><div className="mx-auto mt-8 flex max-w-md justify-between gap-2">{stages.map((item, index) => <div className="flex-1" key={item}><div className={`h-1.5 rounded-full ${index <= stage ? "bg-[#ffb34b]" : "bg-white/15"}`} /></div>)}</div></div><div className="mt-8 grid gap-4 lg:grid-cols-2"><DaySkeleton /><DaySkeleton /></div></main></div>;
  return <div className="min-h-screen bg-[#f7f2e7] text-[#123a35]"><SiteHeader /><main className="mx-auto max-w-[1440px] px-5 py-7 lg:px-10 lg:py-10"><Link href="/planner" className="inline-flex items-center gap-2 text-sm font-bold text-[#5c7770] transition-colors hover:text-[#e6651b]"><ArrowLeft className="h-4 w-4" /> Refine travel details</Link>
    <section className="mt-5 overflow-hidden rounded-[2rem] bg-[#123a35] text-white shadow-[0_22px_50px_-30px_rgba(18,58,53,.6)]"><div className="relative grid gap-7 p-6 lg:grid-cols-[1.1fr_.9fr] lg:p-9"><div className="relative z-10"><p className="atlas-label text-[#ffb34b]">Your forged itinerary</p><div className="mt-3 flex flex-wrap items-end gap-x-5 gap-y-2"><h1 className="font-display text-5xl tracking-[-.07em] sm:text-6xl">{trip.destination.name}</h1><span className="mb-1 rounded-full bg-[#e6651b] px-3 py-1 text-xs font-bold">{trip.score}/100 trip fit</span></div><p className="mt-4 max-w-lg text-base leading-7 text-[#c2d4cb]">{trip.destination.description}</p><div className="mt-7 flex flex-wrap gap-x-6 gap-y-3 text-sm font-semibold text-[#e0ebe4]"><span className="flex items-center gap-2"><CalendarDays className="h-4 w-4 text-[#ffb34b]" /> {formatDateRange(trip.plan.startDate, trip.plan.endDate)}</span><span className="flex items-center gap-2"><UsersRound className="h-4 w-4 text-[#ffb34b]" /> {travellers} traveller{travellers === 1 ? "" : "s"}</span><span className="flex items-center gap-2"><WalletCards className="h-4 w-4 text-[#ffb34b]" /> {formatInr(trip.budget.total)}</span></div></div><div className="relative overflow-hidden rounded-[1.5rem] bg-[#254d47]"><img src={trip.destination.image} alt={trip.destination.name} className="absolute inset-0 h-full w-full object-cover opacity-65" /><div className="absolute inset-0 bg-gradient-to-br from-[#123a35]/20 to-[#123a35]/65" /><div className="absolute bottom-5 left-5 right-5 rounded-2xl bg-[#fffdf8]/92 p-4 text-[#123a35]"><p className="atlas-label text-[#e6651b]">Trip signal</p><p className="mt-1 font-display text-xl tracking-[-.04em]">{trip.plan.travelStyle} pace · {trip.plan.interests.slice(0, 3).join(" · ")}</p></div></div></div></section>
    <section className="mt-7 grid gap-5 md:grid-cols-3"><Metric label="Estimated total" value={formatInr(trip.budget.total)} icon={<WalletCards className="h-5 w-5" />} /><Metric label="Cost per person" value={formatInr(Math.round(trip.budget.total / Math.max(1, travellers)))} icon={<UsersRound className="h-5 w-5" />} /><Metric label="Route movement" value={`${trip.totalDistance} km · ${trip.travelTime}`} icon={<Navigation className="h-5 w-5" />} /></section>
    <section className="mt-10 grid gap-8 xl:grid-cols-[minmax(0,1fr)_460px]"><div><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="atlas-label text-[#e6651b]">Day-by-day itinerary</p><h2 className="mt-2 font-display text-4xl tracking-[-.06em]">A route with some room in it.</h2></div><p className="text-sm font-semibold text-[#647d76]">{activityCount} moments across {trip.days.length} day{trip.days.length === 1 ? "" : "s"}</p></div><div className="mt-6 grid gap-3">{trip.days.map((item, index) => { const open = index === activeDay; return <article key={item.day} className={`overflow-hidden rounded-[1.45rem] border transition-all ${open ? "border-[#123a35]/20 bg-[#fffdf8] shadow-[0_18px_35px_-30px_rgba(18,58,53,.45)]" : "border-[#123a35]/10 bg-[#fffaf1]"}`}><button onClick={() => { setActiveDay(index); setSelectedId(item.activities[0]?.id); }} className="flex w-full items-center justify-between gap-4 p-5 text-left"><div className="flex items-center gap-4"><span className={`grid h-10 w-10 place-items-center rounded-full text-xs font-black ${open ? "bg-[#e6651b] text-white" : "bg-[#e3eee6] text-[#123a35]"}`}>{String(item.day).padStart(2, "0")}</span><div><p className="atlas-label text-[#e6651b]">Day {item.day}</p><h3 className="mt-1 font-display text-2xl tracking-[-.04em]">{item.title}</h3><p className="mt-1 text-xs text-[#6a837c]">{item.subtitle}</p></div></div><ChevronDown className={`h-5 w-5 text-[#e6651b] transition-transform ${open ? "rotate-180" : ""}`} /></button>{open && <div className="border-t border-[#123a35]/10 px-4 pb-5 pt-2 sm:px-5"><div className="divide-y divide-[#123a35]/10">{item.activities.map((activity) => <ActivityCard key={activity.id} activity={activity} selected={selectedId === activity.id} saved={saved.includes(activity.id)} onSelect={() => setSelectedId(activity.id)} onSave={() => saveActivity(activity.id)} onReplace={() => setReplaceTarget(activity)} />)}</div><div className="mt-5 flex flex-wrap gap-2"><ActionButton icon={<RefreshCw className="h-3.5 w-3.5" />} text="Regenerate day" onClick={() => adjustDay("regenerate")} /><ActionButton icon={<WalletCards className="h-3.5 w-3.5" />} text="Make this day cheaper" onClick={() => adjustDay("cheaper")} /><ActionButton icon={<Timer className="h-3.5 w-3.5" />} text="Make this day more relaxed" onClick={() => adjustDay("relaxed")} /></div></div>}</article>; })}</div></div>
      <aside className="xl:sticky xl:top-24 xl:h-fit"><RouteMap destination={trip.destination} activities={day.activities} selectedId={selectedId} onSelect={setSelectedId} /><BudgetSummary trip={trip} /><TripSummary trip={trip} onShare={share} /></aside></section>
  </main><ReplaceDialog target={replaceTarget} onOpenChange={(open) => !open && setReplaceTarget(null)} onReplace={replaceActivity} /></div>;
}

function Metric({ label, value, icon }: { label: string; value: string; icon: React.ReactNode }) { return <div className="rounded-2xl border border-[#123a35]/10 bg-[#fffdf8] p-5"><div className="flex items-center gap-2 text-[#e6651b]">{icon}<span className="atlas-label">{label}</span></div><p className="mt-3 font-display text-2xl tracking-[-.04em]">{value}</p></div>; }
function ActionButton({ icon, text, onClick }: { icon: React.ReactNode; text: string; onClick: () => void }) { return <button onClick={onClick} className="inline-flex items-center gap-1.5 rounded-full border border-[#123a35]/15 bg-[#fffdf8] px-3 py-2 text-xs font-bold text-[#355752] transition-colors hover:border-[#e6651b] hover:text-[#e6651b]">{icon}{text}</button>; }
function ActivityCard({ activity, selected, saved, onSelect, onSave, onReplace }: { activity: Activity; selected: boolean; saved: boolean; onSelect: () => void; onSave: () => void; onReplace: () => void }) { return <div onClick={onSelect} className={`grid cursor-pointer gap-3 py-4 transition-colors sm:grid-cols-[52px_1fr_auto] ${selected ? "rounded-xl bg-[#f4f0e6] px-3 sm:px-4" : "px-1 sm:px-2"}`}><span className="font-mono text-xs font-bold text-[#68837c] sm:pt-1">{activity.time}</span><div><div className="flex flex-wrap items-center gap-2"><p className="font-bold">{activity.title}</p><span className={`rounded-full px-2 py-1 text-[10px] font-black ${hues[activity.category] ?? hues["Local pick"]}`}>{activity.category}</span></div><p className="mt-1 text-sm leading-6 text-[#627d75]">{activity.description}</p><div className="mt-2 flex flex-wrap gap-x-3 gap-y-1 text-xs font-semibold text-[#69827c]"><span>{activity.duration}</span><span>•</span><span>{activity.distance} from last stop</span></div></div><div className="flex items-start justify-between gap-2 sm:flex-col sm:items-end"><p className="text-sm font-bold text-[#e6651b]">{activity.cost ? formatInr(activity.cost) : "Free"}</p><div className="flex gap-1"><button onClick={(event) => { event.stopPropagation(); onSave(); }} className={`grid h-8 w-8 place-items-center rounded-full border transition-colors ${saved ? "border-[#e6651b] bg-[#e6651b] text-white" : "border-[#123a35]/12 bg-white text-[#53716a] hover:text-[#e6651b]"}`} aria-label="Save activity"><Heart className={`h-3.5 w-3.5 ${saved ? "fill-current" : ""}`} /></button><button onClick={(event) => { event.stopPropagation(); onReplace(); }} className="grid h-8 w-8 place-items-center rounded-full border border-[#123a35]/12 bg-white text-[#53716a] hover:text-[#e6651b]" aria-label="Replace activity"><PencilLine className="h-3.5 w-3.5" /></button></div></div></div>; }
function BudgetSummary({ trip }: { trip: ForgedTrip }) { const rows = [["Transportation", trip.budget.transportation, "#97b8b0"], ["Hotels", trip.budget.hotels, "#456e66"], ["Food", trip.budget.food, "#e6651b"], ["Activities", trip.budget.activities, "#f0ae54"], ["Miscellaneous", trip.budget.miscellaneous, "#b5c8c1"]]; return <section className="mt-5 rounded-[1.5rem] border border-[#123a35]/10 bg-[#fffdf8] p-5"><div className="flex items-center justify-between"><div><p className="atlas-label text-[#e6651b]">Budget summary</p><h3 className="mt-1 font-display text-2xl tracking-[-.04em]">Your spend, in view.</h3></div><WalletCards className="h-5 w-5 text-[#e6651b]" /></div><div className="mt-5 grid gap-3">{rows.map(([label, value, colour]) => <div key={label as string}><div className="flex justify-between text-xs font-bold text-[#54716a]"><span>{label}</span><span>{formatInr(value as number)}</span></div><div className="mt-1.5 h-1.5 overflow-hidden rounded-full bg-[#eff3ed]"><div className="h-full rounded-full" style={{ width: `${((value as number) / trip.budget.total) * 100}%`, backgroundColor: colour as string }} /></div></div>)}</div><div className="mt-5 flex items-end justify-between border-t border-[#123a35]/10 pt-4"><span className="text-sm font-bold">Total estimate</span><span className="font-display text-2xl tracking-[-.04em]">{formatInr(trip.budget.total)}</span></div></section>; }
function TripSummary({ trip, onShare }: { trip: ForgedTrip; onShare: () => void }) { const exported = () => toast.success("Your itinerary export is prepared"); const saved = () => toast.success("Trip saved to your TripsForge notes"); return <section className="mt-5 rounded-[1.5rem] bg-[#123a35] p-5 text-white"><div className="flex items-center justify-between"><p className="atlas-label text-[#ffb34b]">Trip summary</p><span className="h-2 w-2 rounded-full bg-[#e6651b]" /></div><div className="mt-4 grid grid-cols-2 gap-4 border-b border-white/20 pb-5 text-sm"><div><p className="text-white/65">Activities</p><p className="mt-1 font-display text-2xl">{trip.days.reduce((sum, day) => sum + day.activities.length, 0)}</p></div><div><p className="text-white/65">Trip style</p><p className="mt-1 font-display text-2xl">{trip.plan.travelStyle}</p></div><div className="col-span-2"><p className="text-white/65">Interests</p><p className="mt-1 text-sm font-bold">{trip.plan.interests.join(" · ")}</p></div></div><div className="mt-5 grid grid-cols-3 gap-2"><button onClick={onShare} className="grid place-items-center gap-1 rounded-xl bg-white/12 px-2 py-3 text-xs font-bold transition-colors hover:bg-white/20"><Share2 className="h-4 w-4" /> Share</button><button onClick={saved} className="grid place-items-center gap-1 rounded-xl bg-white/12 px-2 py-3 text-xs font-bold transition-colors hover:bg-white/20"><Heart className="h-4 w-4" /> Save</button><button onClick={exported} className="grid place-items-center gap-1 rounded-xl bg-[#e6651b] px-2 py-3 text-xs font-bold transition-colors hover:bg-[#f27831]"><Download className="h-4 w-4 text-[#fff4de]" /> Export</button></div></section>; }
function ReplaceDialog({ target, onOpenChange, onReplace }: { target: Activity | null; onOpenChange: (open: boolean) => void; onReplace: () => void }) { return <Dialog open={Boolean(target)} onOpenChange={onOpenChange}><DialogContent className="border-[#123a35]/10 bg-[#fffdf8] text-[#123a35]"><DialogHeader><p className="atlas-label text-[#e6651b]">Route alternative</p><DialogTitle className="font-display text-3xl tracking-[-.05em]">A nearby, better-fitting stop.</DialogTitle><DialogDescription className="leading-6 text-[#668078]">Swap <strong className="text-[#123a35]">{target?.title}</strong> for a local alternative while keeping your day’s route coherent.</DialogDescription></DialogHeader><div className="rounded-2xl bg-[#f2eddf] p-4"><p className="text-sm font-bold">What will change?</p><ul className="mt-2 grid gap-2 text-sm text-[#58736c]"><li>• A comparable experience near your existing route</li><li>• An estimated cost about 15% lower</li><li>• All other day moments stay in place</li></ul></div><DialogFooter><button onClick={() => onOpenChange(false)} className="rounded-full px-4 py-2.5 text-sm font-bold text-[#5b756e]">Keep current stop</button><button onClick={onReplace} className="inline-flex items-center gap-2 rounded-full bg-[#123a35] px-4 py-2.5 text-sm font-bold text-white">Replace activity <Sparkles className="h-4 w-4 text-[#ffb34b]" /></button></DialogFooter></DialogContent></Dialog>; }
